### ISSUE TITLE
Add a LICENSE?

### ISSUE THREAD

**Issue by vedantkarandikar** [pmillspaugh/weeksofyourlife#10]
From the actual content, the site does mention that this repo is open source. But I wanted to play around with the code and embed a non-editable version of the site in my website. Is that fair game?

Since theres no LICENSE I didn't want to assume.

Thanks,

**Comment by pmillspaugh** [comment]
Hey @vedantkarandikar — thanks for asking! Yep, that is totally fine. I'll also add a license.
