### ISSUE TITLE
Delay in birthdate setting

### ISSUE THREAD

**Issue by zanovis** [pmillspaugh/weeksofyourlife#6]
Awesome site, I was just searching for a local tool like this yesterday! 

I think you're aware of this, but there's significant delay (~10seconds) in setting the last parameter in birthdate (Firefox 121.0)

**Comment by pmillspaugh** [comment]
Thanks for opening this issue, @zanovis! Fixed/improved in #7. 

Initially I was resetting birthdate on every date input change event, which was queuing the unnecessary intermediate changes and trying to re-render the entire grid of weeks. That PR refactored to only update birthdate and re-render the grid `onblur`, i.e. when the date input becomes unfocused.
