### ISSUE TITLE
Give some clues for noobs

### ISSUE THREAD

**Issue by frukto** [pmillspaugh/weeksofyourlife#9]
I like this project, but am completely new to the TS ecosystem. Can you give me some hints how to run the code and play around with it. Please don't be mad if this a stupid request for you!

**Comment by pmillspaugh** [comment]
Not at all! Thanks for asking.

1. Fork then clone this repo on the command line: `git clone https://github.com/frukto/weeksofyourlife.git`*
2. (If you haven't already) Download Node.js, which comes with npm: [nodejs.org](https://nodejs.org/en)
3. Install dependencies: `npm install`**
4. Run the local server: `npm run dev`
5. Open http://localhost:3000 in your browser
6. Play around with the code 🙂. E.g. open `src/app/page.tsx`, edit some text in the `<footer>`, and hit save—the text should immediately update in your browser.

_*I inserted your GitHub username into the clone URL, which should work after you've forked.
**I use a package manager called [pnpm](https://pnpm.io/), which is basically the same as npm. So you could also run `pnpm install`._

**Comment by pmillspaugh** [comment]
Let me know if you have any other questions! This project is a Next.js app, so the [Next docs](https://nextjs.org/docs) could be a helpful place to learn about the project structure.

**Comment by frukto** [comment]
Awesome, that's all I need for the moment!
